[build]
command = "npm run build"
publish = "../build"
# functions = "src"
edge_functions = "src/edge"

[dev]
targetPort = 5178
command = "npm run dev"
framework = "#custom"
# publish = "../src"
publish = "../build"
port = 8888

[functions]
directory = "src"
# node_bundler = "esbuild"

[[edge_functions]]
# directory = "src/edge"
path = "/fetch"
function = "ollo"

# [[redirects]]
# from = "/functions/*"
# to = "/.netlify/functions/:splat"
# status = 200

# [[redirects]]
# from = "http://fetch/*"
# from = "https://fetch/*"
# to = "/.netlify/functions/fetch/:splat"
# status = 200
