[build]
command = "npm run build"
publish = "../build"
# functions = "src"

[dev]
targetPort = 5173
command = "npm run dev"
framework = "#custom"
# publish = "../src"
publish = "../build"
port = 8888

[functions]
directory = "src"
# node_bundler = "esbuild"

[[redirects]]
from = "/functions/*"
to = "/.netlify/functions/:splat"
status = 200
