[build]
# base = "/"
command = "npm run build"
publish = "build"

[dev]
targetPort = 5173
command = "npm run dev"
framework = "#custom"
publish = "src"
port = 8888

[functions]
directory = "functions"
# node_bundler = "esbuild"
