[build]
command = "npm run build"
publish = "build"
# functions = "functions/src"

[dev]
targetPort = 5173
command = "npm run dev"
framework = "#custom"
publish = "build"
port = 8888

# [functions]
# directory = "functions/src"
# node_bundler = "esbuild"

